[project]
name = "hope-smart-import"
version = "0.5.1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "django-admin-extra-buttons",
  "hope-flex-fields",
  "openpyxl",
]

[dependency-groups]
dev = [
  "bump2version",
  "django-webtest",
  "factory-boy",
  "ipython",
  "mypy",
  "pdbpp",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "pytest-echo",
  "ruff",
  "tox",
]

docs = [
  "mkdocs",
  "mkdocs-awesome-pages-plugin",
  "mkdocs-material",
  "mkdocstrings-python",
]
